### ISSUE TITLE
Give user an error message if ES fails to index a KML file

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1633]
Currently if a user uploads a KML file that ES can't index, the user doesn't get an error message, meaning he/she doesn't know the KML needs to be fixed. Can we return an error message (with the specific issue, if possible) if the KML doesn't index in ES?

**Comment by kueda** [comment]
Can you provide an example of such a KML file?

**Comment by tiwane** [comment]
Patrick fixed it on our end, but it looks like it was a KML that had duplicate consecutive coordinates. https://groups.google.com/forum/#!topicsearchin/inaturalist/kml$20AND$20before$3A2018$2F01$2F24/inaturalist/3iJ3-D-rLZo

**Comment by kueda** [comment]
By "Patrick fixed it on our end" do you mean that this was fixed and we should close this issue?

**Comment by tiwane** [comment]
Sorry. Patrick fixed that one instance (by removing the duplicate coordinate) but the issue still stands overall.

**Comment by pleary** [comment]
if I recall correctly, I fixed one instance of the problem. PostgreSQL happily accepted a geom which had duplicate consecutive coordinates, but Elasticsearch wouldn't index the geom, so the place was indexed without its geometry (see `double_check_index` in place_index). Running `ST_RemoveRepeatedPoints` in psql against the geom fixed the problem. Maybe that's something we could catch and fix in something like the `double_check_index` step of indexing places

**Comment by kueda** [comment]
I can add this file to staging and it works fine despite duplicate coordinates:

```kml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
  <name>test.kml</name>
  <Placemark>
    <name>Untitled Polygon</name>
    <Polygon>
      <tessellate>1</tessellate>
      <outerBoundaryIs>
        <LinearRing>
          <coordinates>
            -121.8457888538824,37.92388739254731,0
            -121.8336852364004,37.89988354841462,0
            -121.8066578792879,37.92088803254986,0
            -121.8066578792879,37.92088803254986,0
            -121.8066578792879,37.92088803254986,0
            -121.8066578792879,37.92088803254986,0
            -121.8066578792879,37.92088803254986,0
            -121.8066578792879,37.92088803254986,0
            -121.8060695551262,37.92215267329344,0
            -121.8116483510131,37.946875069078,0
            -121.8457888538824,37.92388739254731,0 
          </coordinates>
        </LinearRing>
      </outerBoundaryIs>
    </Polygon>
  </Placemark>
</Document>
</kml>
```

Am I missing something, or was there some other problem with the original KML file?

**Comment by tiwane** [comment]
FWIW, the OP in the Google Group sent the KML file he had used to make the place, and I made [this place](https://www.inaturalist.org/places/incredible-test-place) with it. I'm unable to select it for a project, which is the original problem he had. 

Here's what he wrote in his reply "this is the original KML file used to create the place "Parco agronaturale della Dora Riparia". In second moment I have modified the poligon directly on iNaturalist. Doing this, I noticed that some nodes seemed to be composed by a huge amount of points. I checked the iNaturalist polygon now and the problem seems to be not present anymore."

Not sure if he edited the polygon on iNat before posting in the Google Group. 

[Here's the KML](https://www.dropbox.com/s/kt3mfsfu8p4f40a/inat%20%281%29.kml?dl=0).
